---
title: "Biodiversity Analysis"
author: "Sola Takahashi"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.path = "../figures/04_Biodiversity")
```

# Setting the Environment

## Set the seed
```{r set-seed}
set.seed(158369)
```


## Load Libraries
```{r load-packages}
pacman::p_load(tidyverse, devtools, patchwork, iNEXT, phyloseq, 
               install = FALSE)
```


## Load in Data
```{r load-data}
load("data/02_PreProcessing/raw_preprocessed_physeq.RData")
raw_preprocessed_physeq

# Intuition Check
min(sample_sums(raw_preprocessed_physeq))
# output: 1836

# Make a metadata dataframe
metadata_df <- 
  raw_preprocessed_physeq %>%
  sample_data() %>%
  data.frame() 

#head(metadata_df)

# Setting colors for the stations
station_colors <- c(
  "Shipping Channel" = "dodgerblue4",
  "Aransas Bay" = "dodgerblue2",
  "Copano West" = "#D9CC3C",
  "Copano East" = "#A0E0BA",
  "Mesquite Bay" = "#00ADA7")


```


# Goals

1. Calculate the Hill Diversity of the samples
2. Evaluate the rarefaction curves
3. Evaluate the Diversity values
4. Make notes of specific samples and their seq depth 

# Diversity Calculations with iNEXT

```{r calc-div}
# prepare input data
iNEXT_input_df <-
  raw_preprocessed_physeq %>%
  otu_table() %>%
  data.frame()

# Quick check
dim(iNEXT_input_df)

# Run iNEXT: Calculate Hill Numbers
# Note that: Species in ROWS and samples in COLUMNS
# Remember to set the seed!
# iNEXT_data <- iNEXT(iNEXT_input_df, q = c(0,1,2), 
#                    datatype = "abundance")

# Save the file
#save(iNEXT_data, file = "data/04_Biodiversity/iNEXT_data.RData")
```

# Evaluate the Diversity
```{r load-div}
load("data/04_Biodiversity/iNEXT_data.RData")
str(iNEXT_data)
typeof(iNEXT_data)
# size based estimator is the best for incidence data
# this type of list is less stringent data standards (S3), don't need anchoring of sample/column names (S4 - with phyloseq object)

```


# Plot Diversity
```{r plot-rarefaction}
# Prepare colors
color_df <-
  iNEXT_input_df %>%
  colnames() %>%
  data.frame()
  
# Check
head(color_df)

# Rename column
colnames(color_df)[1] <- "names"

# Make a helper dataframe for plotting with colors
# replace . and remove X
iNEXT_color_df <-
color_df %>%
  # fix the names for merging
  mutate(names = gsub(names, pattern = "[.]", replace = "-"), 
         names = gsub(names, pattern = "X", replace = "")) %>%
  # merge iwth metadata
  left_join(metadata_df, by = "names") %>%
  # merge with colors for plotting with ggNEXT
  left_join(data.frame(station_colors = station_colors,
            station = names(station_colors)),
            by = "station")
  

# END HERE

```

# Plot Rarefaction with 'ggiNEXT'
```{r ggiNEXT, fig.width = 8, fig.height= 3.5}
# Plot rarefaction
# rarefaction v extrapolation curve, type = 1

# Order q: 
# 0 = RIchness/ total number taxa
# 1 = Exponential Shannon/ Number of common taxa
# 2 = Inverse simpson / Number of dominant taxa 

ggiNEXT(iNEXT_data, type = 1, facet.var = "Order.q") +
  facet_wrap(~Order.q, scales = "fixed") +
  scale_color_manual(values = iNEXT_color_df$station_colors, guide = FALSE) +
  scale_fill_manual(values = iNEXT_color_df$station_colors, guide = FALSE) +
  scale_shape_manual(values = base::rep(17, nsamples(raw_preprocessed_physeq)), 
                     guide = FALSE) +
  theme(legend.position = "none")
# ggplot shapes, 17= triangle
# Analysis:
# in soils and water -> microbial seed bank of a bunch of dormant species 
# 

```




